# Generated by Django 5.0.8 on 2025-01-26 18:09

import apps.logger.models.logs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(
                blank=True, encoder=apps.logger.models.logs.PrettyJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="errors",
            field=models.JSONField(
                blank=True, encoder=apps.logger.models.logs.PrettyJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="new_data",
            field=models.JSONField(
                blank=True, encoder=apps.logger.models.logs.PrettyJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="old_data",
            field=models.JSONField(
                blank=True, encoder=apps.logger.models.logs.PrettyJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_data",
            field=models.JSONField(
                blank=True, encoder=apps.logger.models.logs.PrettyJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="response_data",
            field=models.JSONField(
                blank=True, encoder=apps.logger.models.logs.PrettyJSONEncoder, null=True
            ),
        ),
    ]
