# Generated by Django 5.0.8 on 2025-01-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0002_alter_auditlog_details_alter_auditlog_errors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("POST", "Create"),
                    ("PATCH", "Update Partial"),
                    ("PUT", "Update Full"),
                    ("DELETE", "Delete"),
                ],
                max_length=50,
            ),
        ),
    ]
