# Generated by Django 5.0.8 on 2025-01-26 19:27

import apps.logger.models.logs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0003_alter_auditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="changed_fields",
            field=models.JSONField(
                blank=True, encoder=apps.logger.models.logs.PrettyJSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="execution_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="headers",
            field=models.JSONField(
                blank=True, encoder=apps.logger.models.logs.PrettyJSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="log_entry",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("POST", "Create"),
                    ("PATCH", "Update Partial"),
                    ("PUT", "Update Full"),
                    ("DELETE", "Delete"),
                    ("FAILED_AUTHENTICATION", "Failed Authentication"),
                ],
                max_length=50,
            ),
        ),
    ]
